# Generated by Django 2.2.12 on 2020-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200417_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='R1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.BigIntegerField()),
            ],
        ),
    ]
